-- Migration 009: User manage token
--
-- Adds a secret per-user token used to gate the "edit your profile" page
-- (/account/[token]). The handle is public (it is the booking URL), so it must
-- never be the key that authorizes profile edits. This token is the secret a
-- business owner receives in their welcome email and uses to come back and edit.
--
-- Mirrors the meetings.manage_token pattern (24-char nanoid generated by the app).

ALTER TABLE users ADD COLUMN IF NOT EXISTS manage_token text UNIQUE;

-- Backfill existing users with a random token so their edit link works too.
UPDATE users
SET manage_token = replace(gen_random_uuid()::text, '-', '')
WHERE manage_token IS NULL;

CREATE INDEX IF NOT EXISTS users_manage_token_idx ON users(manage_token);
